### ISSUE TITLE
local build runs into error

### ISSUE THREAD

**Issue by I2olanD** [DivanteLtd/next#159]
After installing all dependencies and running the build command:
```
yarn build:ct:tools
```
i get following output:

```yarn run v1.21.1
$ yarn build:ct:api-client && yarn build:ct:helpers && yarn build:ct:composables
$ cd packages/commercetools/api-client && yarn build
warning package.json: No license field
$ rollup -c

src/index.ts → lib/index.cjs.js, lib/index.es.js...
(!) Circular dependencies
src/index.ts -> src/api/getProduct/index.ts -> src/index.ts
src/index.ts -> src/api/getProduct/index.ts -> src/helpers/search/index.ts -> src/index.ts
src/index.ts -> src/api/getCategory/index.ts -> src/index.ts
...and 7 more
created lib/index.cjs.js, lib/index.es.js in 4.1s
$ cd packages/commercetools/helpers && yarn build
warning package.json: No license field
$ rollup -c

src/index.ts → lib/index.cjs.js, lib/index.es.js...
[!] (plugin rpt2) Error: /Users/olah/DEV/work/next/packages/commercetools/helpers/src/index.ts(136,3): semantic error TS2322: Type '{ title: string; id: string; price: { regular: number; }; image: string; qty: any; configuration: AgnosticProductAttribute[]; }[]' is not assignable to type 'UiCartProduct[]'.
  Type '{ title: string; id: string; price: { regular: number; }; image: string; qty: any; configuration: AgnosticProductAttribute[]; }' is not assignable to type 'UiCartProduct'.
    Types of property 'configuration' are incompatible.
      Type 'AgnosticProductAttribute[]' is not assignable to type 'UiCartProductConfiguration[]'.
        Type 'AgnosticProductAttribute' is not assignable to type 'UiCartProductConfiguration'.
          Types of property 'value' are incompatible.
            Type 'string | Object' is not assignable to type 'string'.
              Type 'Object' is not assignable to type 'string'.
src/index.ts
Error: /Users/olah/DEV/work/next/packages/commercetools/helpers/src/index.ts(136,3): semantic error TS2322: Type '{ title: string; id: string; price: { regular: number; }; image: string; qty: any; configuration: AgnosticProductAttribute[]; }[]' is not assignable to type 'UiCartProduct[]'.
  Type '{ title: string; id: string; price: { regular: number; }; image: string; qty: any; configuration: AgnosticProductAttribute[]; }' is not assignable to type 'UiCartProduct'.
    Types of property 'configuration' are incompatible.
      Type 'AgnosticProductAttribute[]' is not assignable to type 'UiCartProductConfiguration[]'.
        Type 'AgnosticProductAttribute' is not assignable to type 'UiCartProductConfiguration'.
          Types of property 'value' are incompatible.
            Type 'string | Object' is not assignable to type 'string'.
              Type 'Object' is not assignable to type 'string'.
    at error (/Users/olah/DEV/work/next/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/Users/olah/DEV/work/next/node_modules/rollup/dist/shared/node-entry.js:11874:12)
    at Object.error (/Users/olah/DEV/work/next/node_modules/rollup/dist/shared/node-entry.js:12908:24)
    at Object.error (/Users/olah/DEV/work/next/node_modules/rollup/dist/shared/node-entry.js:12077:38)
    at RollupContext.error (/Users/olah/DEV/work/next/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
    at lodash_3 (/Users/olah/DEV/work/next/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24958:23)
    at arrayEach (/Users/olah/DEV/work/next/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
    at forEach (/Users/olah/DEV/work/next/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
    at printDiagnostics (/Users/olah/DEV/work/next/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24931:5)
    at Object.transform (/Users/olah/DEV/work/next/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27373:17)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by I2olanD** [comment]
After running the other commands provided in the package.json it worked :).
